[tool.poetry]
name = "pylandscape"
version = "0.1.3"
description = "Python package to explore the loss landscape of Machine Learning models"
authors = ["Tommaso Baldi"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/balditommaso/PyLandscape"
repository = "https://github.com/balditommaso/PyLandscape"
packages = [
    { include = "pylandscape" },
    { include = "pylandscape/mc_utils" }
]


[tool.poetry.dependencies]
python = ">=3.11,<3.14"
numpy = ">=1.26"
torch = ">=2.10"
tqdm = "*"
torchvision = ">=0.25"
scipy = "^1.17.1"
pyhessian = "*"
brevitas = { version = ">=0.12.1", optional = true }

[tool.poetry.extras]
mode-connectivity = ["brevitas"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
